# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "ex_tree"
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["subicura"]
  s.date = "2012-04-25"
  s.description = "tree plugin"
  s.email = "subicura@subicura.com"
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "MIT_LICENSE",
    "README",
    "Rakefile",
    "VERSION",
    "ex_tree.gemspec",
    "lib/ex_tree.rb"
  ]
  s.homepage = "http://github.com/subicura/ex_tree"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "tree plugin"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

